Start the desktop-session and report the ID

diff --git a/usr/share/simple-interactive/simple.sh.erb b/usr/share/simple-interactive/simple.sh.erb
--- a/usr/share/simple-interactive/simple.sh.erb
+++ b/usr/share/simple-interactive/simple.sh.erb
@@ -142,9 +142,9 @@
 # Several standard variables, such as SLURM_JOB_ID, SLURM_JOB_NAME and
 # SLURM_NTASKS, are made available by the scheduler.
 
-#=====================
-#  Results directory
-#---------------------
+#============================
+#  Results/Metadata directory
+#----------------------------
 # By convention, job's submitted with `flight-job` are expected to save their
 # results to RESULTS_DIR.  `flight-job` provides easy access to any files
 # saved there.
@@ -152,8 +152,18 @@
 # If RESULTS_DIR is modified, `flight-job` will be unable to track the job's
 # results.
 #
+# The CONTROLS_DIR is used internally to track various flight-job data files.
+# This is primarily used to store the VNC settings for the interactive
+# sesison.
+#
 # WARNING: The script must not change directory prior to this line.
 RESULTS_DIR="$(pwd)/${SLURM_JOB_NAME}-outputs/$SLURM_JOB_ID"
+CONTROLS_DIR="$(pwd)/${SLURM_JOB_NAME}-controls/$SLURM_JOB_ID"
+mkdir -p "$CONTROLS_DIR"
+mkdir -p "$RESULTS_DIR"
+FLIGHT_DESKTOP_STDOUT="$CONTROLS_DIR"/flight-desktop-stdout
+FLIGHT_DESKTOP_STDERR="$CONTROLS_DIR"/flight-desktop-stderr
+FLIGHT_DESKTOP_STATUS="$CONTROLS_DIR"/flight-desktop-status
 
 # ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
 #  >>>> YOUR WORKLOAD
@@ -166,7 +176,7 @@ RESULTS_DIR="$(pwd)/${SLURM_JOB_NAME}-outputs/$SLURM_JOB_ID"
 # module load apps/imb
 
 #===========================
-#  Create results directory
+#  Results directory
 #---------------------------
 # By convention, job's submitted with `flight-job` are expected to save their
 # results to RESULTS_DIR.  `flight-job` provides easy access to any files
@@ -178,7 +188,6 @@ RESULTS_DIR="$(pwd)/${SLURM_JOB_NAME}-outputs/$SLURM_JOB_ID"
 #
 # RESULTS_DIR has already been set to "${WORKING_DIR}/${SLURM_JOB_NAME}-outputs/$SLURM_JOB_ID".
 echo "Your results will be stored in: $RESULTS_DIR"
-mkdir -p "$RESULTS_DIR"
 
 #===============================
 #  Application launch commands
@@ -189,6 +198,22 @@ echo "Executing job commands, current working directory is $(pwd)"
 
 # REPLACE THE FOLLOWING WITH YOUR APPLICATION COMMANDS
 
-echo "Hello, <%= questions.workload.answer %>!" > $RESULTS_DIR/test.output
-echo "This is an example job. It ran on `hostname -s` (as `whoami`)." >> $RESULTS_DIR/test.output
-echo "Output file has been generated, please check $RESULTS_DIR/test.output"
+# Install the application - Demo R
+flight env create gridware
+flight env activate gridware
+gridware install apps/R/3/4/2
+module load apps/R
+
+# Additional command-line options (R -h for a list).
+R_OPTIONS=""
+
+# Start R and an empty terminal with flight-desktop
+# NOTE: Standard output must be reported to the FLIGHT_DESKTOP_SESSION
+#       file. Failure to do so will prevent flight-job from tracking
+#       the session.
+flight desktop start \
+  --app "R $_OPTIONS" \
+  --script bash \
+  >"$FLIGHT_DESKTOP_STDOUT" \
+  2>/"$FlIGHT_DESKTOP_STDERR"
+echo $? >"$FLIGHT_DESKTOP_STATUS"
